remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", "~> GITHUB-PAGES-VERSION", group: :jekyll_plugins
title: Computational Social Science Group
description: The Computational Social Science Group at KAIST is a growing community of scholars dedicated to advancing the study of social phenomena through diverse methodological approaches---including computational, quantitative, experimental, and qualitative research. Our mission is to build a vibrant network that connects researchers within KAIST and across institutions, fostering collaboration and dialogue in the broader social science community. Through regular events such as our Brown Bag series and Special Seminars with guest speakers, we aim to create an inclusive space for scholarly exchange, mentorship, and the development of cutting-edge interdisciplinary research.
show_downloads: false
